# I. Introduction

Let's explore salaries data-set. Here we will try predictions with **Support Vector Regression** model.

Here is our task: we have a person comming to interview, who used to be a Partner in former organization. 

She will ask a salay rise - what shall it be?

# 1. Import Libraries

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score

# 2. Import a Data-Set

In [ ]:
se_file_name = "/content/drive/MyDrive/Data analytics course/position_salaries.csv"
se_df = pd.read_csv(se_file_name)
se_df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


For exploration purpose - let's re-create Linear Regression and see - how it been trained.

In [ ]:
#X
inpdependet_var = se_df.iloc[:, 1:2].values # kolonnu indpendet jatāsia kā 2d masīvu, kolonnu jānoodod kā range

#y
dependent_var = se_df.iloc[:, -1].values # viendimensijas masīvs pēdējai kolonnai

In [ ]:
inpdependet_var

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
dependent_var

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

#3. Feature Scaling

Since Salaries vary from levels as per range -> we shall create feature scaling.

To do Feature Scaling, all vactors (here, *independant* and *dependant*) shall be 2D-arrays. 

We know, that *dependand* vector is 1D array - let's start with reshaping of it.

In [ ]:
dependent_var_reshaped = dependent_var.reshape(len(dependent_var),1)
dependent_var_reshaped

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]])

Now, we can do our feature scaling.

In [ ]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
sc_independent_var = sc_X.fit_transform(inpdependet_var)

sc_y = StandardScaler()
sc_dependent_var_reshaped = sc_y.fit_transform(dependent_var_reshaped)

In [ ]:
sc_independent_var #notika scalings

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [ ]:
sc_dependent_var_reshaped

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815],
       [-0.35033854],
       [-0.17428902],
       [ 0.17781001],
       [ 0.88200808],
       [ 2.64250325]])

# 4. Split Data-Set into Training and Test sets

**We will skip it here.**

# 5. Training of Machine Learning Model with Linear Regression

In [ ]:
from sklearn.svm import SVR

svr_reg_model = SVR(kernel="rbf") #iekavās nosaka kerneli

svr_reg_model.fit(sc_independent_var, sc_dependent_var_reshaped)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

**Radial Basis Function** kernel - is one of most popular kernels in SVR.

# 6. Run a Prediction

In [ ]:
y_pred = svr_reg_model.predict(sc_X.transform([[7.5]])) #veic scaling transformcāciju
y_pred

array([0.05014191])

In [ ]:
sc_y.inverse_transform(y_pred) #veic backwards scaling transformcāciju

array([263740.85328003])

# 7. Visualize results



---

**Q 16.1 Build Visualization of SVR by yourself**

In [ ]:
sns.scatterplot(x=inpdependet_var[:,0], y=dependent_var, color="red")
plt.plot(inpdependet_var, svr_reg_model.predict(independent_var), color="blue")



---



In [ ]:
r2_score_svr = r2_score(sc_y.inverse_transform(sc_dependent_var_reshaped[:, 0]), sc_y.inverse_transform(svr_reg_model.predict(sc_independent_var)))
r2_score_svr*100

75.16001070620798

**Smoother Visualization**

In [ ]:
import numpy as np

sc_independent_var_grid = np.arange(min(sc_X.inverse_transform(sc_independent_var)), max(sc_X.inverse_transform(sc_independent_var)), 0.1)
sc_independent_var_grid_reshape = sc_independent_var_grid.reshape(len(sc_independent_var_grid), 1)

sns.scatterplot(x=sc_X.inverse_transform(sc_independent_var[:, 0]), y=sc_y.inverse_transform(sc_dependent_var_reshaped), color="red")
plt.plot(sc_independent_var_grid_reshape, sc_y.inverse_transform(svr_reg_model.predict(sc_X.transform(sc_independent_var_grid_reshape))), color='blue')
